# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.create(user_name: "user1", full_name: "User One", password: "password123")
User.create(user_name: "user2", full_name: "User Two", password: "password456")
User.create(user_name: "johndoe", full_name: "John Doe", password: "password123")
User.create(user_name: "janedoe", full_name: "Jane Doe", password: "letmein")
User.create(user_name: "bobsmith", full_name: "Bob Smith", password: "securepassword")
User.create(user_name: "alicesmith", full_name: "Alice Smith", password: "123456")
User.create(user_name: "michaelbrown", full_name: "Michael Brown", password: "password456")
User.create(user_name: "sarahtaylor", full_name: "Sarah Taylor", password: "sarah123")
User.create(user_name: "davidlee", full_name: "David Lee", password: "david456")
User.create(user_name: "oliviaclark", full_name: "Olivia Clark", password: "olivia789")
User.create(user_name: "emilywong", full_name: "Emily Wong", password: "emilypass")
User.create(user_name: "danielkim", full_name: "Daniel Kim", password: "daniel777")

User.create(user_name: "johndoe", full_name: "John Doe", password: "password123", created_at: Time.now, updated_at: Time.now)
User.create(user_name: "janedoe", full_name: "Jane Doe", password: "letmein", created_at: Time.now, updated_at: Time.now)
User.create(user_name: "bobsmith", full_name: "Bob Smith", password: "securepassword", created_at: Time.now, updated_at: Time.now)
User.create(user_name: "alicesmith", full_name: "Alice Smith", password: "123456", created_at: Time.now, updated_at: Time.now)
User.create(user_name: "michaelbrown", full_name: "Michael Brown", password: "password456", created_at: Time.now, updated_at: Time.now)

Tweet.create(content: "Este es el primer tweet.", created_at: Time.now, updated_at: Time.now, user_id: 1)
Tweet.create(content: "¡Hola, Twitter!", created_at: Time.now, updated_at: Time.now, user_id: 2)
Tweet.create(content: "Esto es un retweet.", created_at: Time.now, updated_at: Time.now, user_id: 3)
Tweet.create(content: "Citando un tweet.", created_at: Time.now, updated_at: Time.now, user_id: 4)
Tweet.create(content: "Respondiendo a un tweet.", created_at: Time.now, updated_at: Time.now, user_id: 5)
Tweet.create(content: "Otro tweet interesante.", created_at: Time.now, updated_at: Time.now, user_id: 1)
Tweet.create(content: "Twitter es increíble.", created_at: Time.now, updated_at: Time.now, user_id: 2)
Tweet.create(content: "Probando retweets.", created_at: Time.now, updated_at: Time.now, user_id: 3)
Tweet.create(content: "Una cita interesante.", created_at: Time.now, updated_at: Time.now, user_id: 4)
Tweet.create(content: "Último tweet del día.", created_at: Time.now, updated_at: Time.now, user_id: 5)

Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 1, user_id: 1)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 2, user_id: 2)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 3, user_id: 3)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 4, user_id: 4)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 5, user_id: 5)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 1, user_id: 2)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 2, user_id: 3)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 3, user_id: 4)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 4, user_id: 5)
Like.create(created_at: Time.now, updated_at: Time.now, tweet_id: 5, user_id: 1)

Bookmark.create(user_id: 1, tweet_id: 1, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 2, tweet_id: 2, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 3, tweet_id: 3, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 4, tweet_id: 4, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 5, tweet_id: 5, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 1, tweet_id: 6, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 2, tweet_id: 7, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 3, tweet_id: 8, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 4, tweet_id: 9, created_at: Time.now, updated_at: Time.now)
Bookmark.create(user_id: 5, tweet_id: 10, created_at: Time.now, updated_at: Time.now)

Retweet.create(user_id: 1, tweet_id: 1, reply_text: "¡Gran tweet!", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 2, tweet_id: 2, reply_text: "Totalmente de acuerdo.", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 3, tweet_id: 3, reply_text: "Me encanta esto.", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 4, tweet_id: 4, reply_text: "Compartiendo este contenido.", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 5, tweet_id: 5, reply_text: "¡Definitivamente vale la pena retweetear!", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 1, tweet_id: 6, reply_text: "Interesante perspectiva.", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 2, tweet_id: 7, reply_text: "Gracias por compartir.", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 3, tweet_id: 8, reply_text: "Esto es increíble.", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 4, tweet_id: 9, reply_text: "Totalmente inspirador.", created_at: Time.now, updated_at: Time.now)
Retweet.create(user_id: 5, tweet_id: 10, reply_text: "¡No puedo dejar de retweetear esto!", created_at: Time.now, updated_at: Time.now)

Hashtag.create(name: "rubyonrails")
Hashtag.create(name: "webdevelopment")
Hashtag.create(name: "programming")

User.create(user_name: "john_doe", full_name: "John Doe", password: "password123")
User.create(user_name: "jane_doe", full_name: "Jane Doe", password: "password456")
User.create(user_name: "bob_smith", full_name: "Bob Smith", password: "password789")
User.create(user_name: "mary_jones", full_name: "Mary Jones", password: "passwordabc")
User.create(user_name: "peter_parker", full_name: "Peter Parker", password: "passworddef")
User.create(user_name: "susan_davis", full_name: "Susan Davis", password: "passwordghi")
User.create(user_name: "david_smith", full_name: "David Smith", password: "passwordjkl")
User.create(user_name: "lisa_johnson", full_name: "Lisa Johnson", password: "passwordmno")
User.create(user_name: "michael_brown", full_name: "Michael Brown", password: "passwordpqr")
User.create(user_name: "sarah_williams", full_name: "Sarah Williams", password: "passwordstu")

Tweet.create(content: "This is my first tweet!", user_id: 1)
Tweet.create(content: "Just had an amazing meal.", user_id: 2)
Tweet.create(content: "Excited for the weekend!", user_id: 3)
Tweet.create(content: "Watching a great movie.", user_id: 4)
Tweet.create(content: "Listening to my favorite song.", user_id: 5)
Tweet.create(content: "Visiting an art gallery today.", user_id: 6)
Tweet.create(content: "Fashion show tonight!", user_id: 7)
Tweet.create(content: "Starting a new fitness routine.", user_id: 8)
Tweet.create(content: "Business meeting in progress.", user_id: 9)
Tweet.create(content: "Health is wealth!", user_id: 10)

Follower.create(user_id: 1, followers: 2, following: 3)
Follower.create(user_id: 2, followers: 3, following: 1)
Follower.create(user_id: 3, followers: 1, following: 2)
Follower.create(user_id: 4, followers: 2, following: 1)
Follower.create(user_id: 5, followers: 1, following: 3)
Follower.create(user_id: 6, followers: 3, following: 2)
Follower.create(user_id: 7, followers: 2, following: 3)
Follower.create(user_id: 8, followers: 1, following: 2)
Follower.create(user_id: 9, followers: 3, following: 1)
Follower.create(user_id: 10, followers: 1, following: 3)